# Generated by Django 3.2.8 on 2022-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=25)),
                ('carbs', models.CharField(max_length=25)),
                ('proteins', models.CharField(max_length=25)),
                ('fats', models.CharField(max_length=25)),
                ('key_ingredient1', models.CharField(max_length=25)),
                ('key_ingredient2', models.CharField(max_length=25)),
                ('key_ingredient3', models.CharField(max_length=25)),
                ('key_ingredient4', models.CharField(max_length=25)),
                ('key_ingredient5', models.CharField(max_length=25)),
                ('item_rating', models.FloatField()),
            ],
        ),
    ]
