# Generated by Django 3.2.8 on 2022-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mail_id', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mail_id', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
