# Generated by Django 3.2.8 on 2022-05-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20220428_1849'),
        ('User', '0002_alter_regularuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=30)),
                ('afood', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=30)),
                ('pfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
    ]
