# Generated by Django 3.2.8 on 2022-05-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_allergyfood_preferredfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergyfood',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.premiumuser'),
        ),
        migrations.AlterField(
            model_name='preferredfood',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
