# Generated by Django 3.2.8 on 2022-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220502_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergyfood',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
