# Generated by Django 3.2.8 on 2022-05-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20220505_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergyfood',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='preferredfood',
            old_name='user_id',
            new_name='user',
        ),
    ]
